name: neural_mcts
channels:
  - pytorch
dependencies:
  - pytorch
  - networkx
  - tqdm
  - seaborn
  - pytest
  - pip
  - pip:
      - wandb
      - stable-baselines3
      - python-tsp
      - multiprocess
  - tensorboard

